version: "3.9"

networks:
  net:
    name: kong-net

services:
  postgres:
    container_name: postgres-kong
    image: postgres:9.6
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: kong
      POSTGRES_DB: kong
      POSTGRES_PASSWORD: kong
    volumes:
      - ./_volumes/postgres/data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "psql -U kong -lqt | cut -d \\| -f 1 | grep -qw kong"]
      interval: 7s
      timeout: 3s
      retries: 7
    networks:
      - net

  kong-migration:
    image: kong
    container_name: kong-migration
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      - KONG_DATABASE=postgres
      - KONG_PG_HOST=postgres
      - KONG_PG_USER=kong
      - KONG_PG_PASSWORD=kong
    command: kong migrations bootstrap
    networks:
      - net

  kong:
    container_name: kong-dev
    image: kong
    ports:
       - "8000:8000"
       - "8443:8443"
       - "8001:8001"
       - "8444:8444"
    environment:
      KONG_DATABASE: postgres
      KONG_PG_HOST: postgres
      KONG_PG_USER: kong
      KONG_PG_DATABASE: kong
      KONG_PG_PASSWORD: kong
      KONG_PROXY_ACCESS_LOG: /logs/proxy_access.log
      KONG_ADMIN_ACCESS_LOG: /logs/admin_access.log
      KONG_PROXY_ERROR_LOG: /logs/proxy_stderr.log
      KONG_ADMIN_ERROR_LOG: /logs/admin_stderr.log
      KONG_ADMIN_LISTEN: 0.0.0.0:8001, 0.0.0.0:8444 ssl
    volumes:
      - ./_volumes/kong/logs:/logs
    depends_on:
      postgres:
        condition: service_healthy
      kong-migration:
        condition: service_completed_successfully
    networks:
      - net
